openapi: '3.0.3'
info:
  title: CP NewsPro Management API
  version: "0.1"
servers:
  - url: https://cp-dev.newshub.pro/mapi
    description: Staging server.
paths:
  /users:
    get:
      summary: Returns a list of users.
      responses:
        '200':
          description: A JSON array of users.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _items:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                  _meta:
                    $ref: '#components/schemas/Meta'
    post:
      summary: Creates a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: New user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users/{userId}:
    get:
      summary: Return a user by ID.
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            $ref: '#components/schemas/ObjectId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    ObjectId:
      type: string
      example: 619277ef8bbbbfac6034aab7

    Meta:
      type: object
      properties:
        total:
          type: integer

    User:
      type: object
      properties:
        _id:
          $ref: '#components/schemas/ObjectId'
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
      required:
        - email
