version: 1
disable_existing_loggers: False
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  superdesk.ws:
    handlers: [ console ]
    level: DEBUG
  worker:
    handlers: [ console ]
    level: WARN
  root:
    handlers: [ console ]
